gold = ['NEM', 'ABX', 'FNV.TO', 'NCM.AX', 'GG',
        'AEM', 'KGC', 'RGLD', 'RRS.L', 'FRES.L',
        'AGG.AX', 'EVN.AX', 'GFI', 'BTO.TO', 'YRI.TO',
        'IMG.TO', 'AGI.TO', 'CEY.L', 'PVG', 'DGC.TO', 'NGD.TO',
        'RRL.AX', 'OGC.TO', 'SBM.AX', 'CG.TO', 'EDV.TO', 'NG.TO',
        'ELD.TO', 'SAR.AX', 'SMF.TO', 'HMY', 'TXG.TO', 'CGG.TO',
        'NSU.TO', 'GUY.TO', 'RSG.AX', 'SEA.TO', 'MUX', 'RIC',
        'PG.TO', 'OSK.TO', 'ALIAF', 'CNL.TO', 'GOR.AX', 
        'POG.L', 'GSS', 'PAF.L', 'AR.TO', 'PRU.AX',
        'TBR.AX', 'BGM.V', 'TGZ.TO', 'SBB.TO',
        'GORO', 'WDO.TO', 'HRT.TO', 'WAF.AX', 'VIT.V', 
        'AOT.V', 'NGQ.TO', 'BDR.AX', 'HUM.L', 'RMS.AX',
        'SLR.AX', 'BSX.TO', 'GCY.AX', 'KOR.TO', 'MOZ.TO', 'BTR.V',
        'HRR.AX', 'PRB.V', 'ALK.AX', 'HAS.AX', 'R.TO', 'JAG.TO', 
        'MAX.TO', 'TNG.AX', 'PEN.AX', 'CAL.TO', 'TLG.AX', 'RUP.V', 
        'GGP.L', 'AAL.V', 'KCN.AX', 'ITH.TO', 'MML.AX', 'GGG.AX', 'VGZ', 
        'ARU.V', 'RMX.TO', 'QBL.AX', 'TSG.L', 'ATC.V', 'KGL.AX', 'TML.TO',
        'IMA.AX', 'DRM.AX', 'RED.AX', 'MTO.V', 'DGR.AX', 'MRC.AX',
        'DNG.TO', 'LIO.V', 'GME.AX', 'LEG.AX', 'BAR.TO', 'ATM.V',
        'EAR.AX', 'KRM.AX', 'FML.AX', 'ORN.AX', 'ER.TO', 'RGD.V',
        'RBX.V', 'LYD.TO', 'TXR.V', 'DEG.AX', 'TAM.AX', 'NGY.AX',
        'CHN.AX', 'GRR.V', 'LG.V', 'GSR.V', 'TRY.AX', 'TNX.TO',
        'TLM.AX', 'ME.TO', 'MJS.V', 'GCM.TO', 'BSR.AX', 'RTG.TO',
        'CAY.AX', 'KTN.V', 'MRP.AX', 'ARE.AX', 'FSY.TO', 'TON.AX', 
        'SRB.L', 'BCN.AX', 'TSG.V', 'MAT.AX', 'IRC.AX', 'ERM.AX', 
        'ORV.TO', 'HMX.V', 'NGE.V', 'SPA.V', 'MAW.TO', 'MNR.TO',
        'ANX.TO', 'SKE.V', 'AAU.L', 'WHY.V', 'NAG.AX', 'GRG.V', 
        'GQC.V', 'AAR.AX', 'AGC.V', 'HAW.AX', 'RUG.V', 'ECR.V',
        'SIH.AX', 'SMC.AX', 'GLN.AX', 'GQM.TO', 'GDP.L', 'SAU.TO',
        'MMV.V', 'GAL.V', 'MMY.V', 'CAS.AX', 'LPK.V', 'GWR.AX', 
        'REX.V', 'CLH.V', 'KG.V', 'AAB.TO', 'IAU.AX', 'AGG.V',
        'BAR.AX', 'DRA.AX', 'OGR.V', 'AGD.V', 'DGO.AX', 'WDG.V', 
        'WKM.V', 'ANK.V', 'AZX.V', 'RRI.V', 'GWA.V', 'MC.V',
        'BRZ.V', 'JPR.AX', 'CRB.AX', 'SWA.V', 'PJX.V', 'OOO.V',
        'AZM.AX', 'AOM.AX', 'RDS.V', 'MUN.V', 'MDI.AX', 'MAE.V',
        'TEN.V', 'HLX.AX', 'AGS.AX', 'LME.V', 'CTM.AX', 'RPX.V', 
        'MSR.AX', 'BAT.V', 'CTO.AX', 'MTU.V', 'RG.V', 'ECC.V', 'IO.V', 'GGA.TO',]

spy = ['MMM', 'AOS', 'ABT', 'ABBV', 'ACN', 'ATVI', 'AYI', 'ADBE', 'AAP', 'AMD', 'AES',
       'AMG', 'AFL', 'A', 'APD', 'AKAM', 'ALK', 'ALB', 'ARE', 'ALXN', 'ALGN', 'ALLE', 'AGN',
       'ADS', 'LNT', 'ALL', 'GOOGL', 'GOOG', 'MO', 'AMZN', 'AEE', 'AAL', 'AEP', 'AXP', 'AIG',
       'AMT', 'AWK', 'AMP', 'ABC', 'AME', 'AMGN', 'APH', 'APC', 'ADI', 'ANSS', 'ANTM', 'AON',
        'APA', 'AIV', 'AAPL', 'AMAT', 'APTV', 'ADM', 'ARNC', 'AJG', 'AIZ', 'T', 'ADSK', 'ADP',
        'AZO', 'AVB', 'AVY', 'BHGE', 'BLL', 'BAC', 'BAX', 'BBT', 'BDX', 'BRK.B', 'BBY', 'BIIB',
        'BLK', 'HRB', 'BA', 'BKNG', 'BWA', 'BXP', 'BSX', 'BHF', 'BMY', 'AVGO', 'BF.B', 'CHRW',
        'CA', 'COG', 'CDNS', 'CPB', 'COF', 'CAH', 'KMX', 'CCL', 'CAT', 'CBOE', 'CBRE', 'CBS', 
        'CELG', 'CNC', 'CNP', 'CTL', 'CERN', 'CF', 'SCHW', 'CHTR', 'CVX', 'CMG', 'CB', 'CHD', 
        'CI', 'XEC', 'CINF', 'CTAS', 'CSCO', 'C', 'CFG', 'CTXS', 'CME', 'CMS', 'KO', 'CTSH', 'CL',
        'CMCSA', 'CMA', 'CAG', 'CXO', 'COP', 'ED', 'STZ', 'GLW', 'COST', 'COTY', 'CCI', 'CSRA',
        'CSX', 'CMI', 'CVS', 'DHI', 'DHR', 'DRI', 'DVA', 'DE', 'DAL', 'XRAY', 'DVN', 'DLR', 
        'DFS', 'DISCA', 'DISCK', 'DISH', 'DG', 'DLTR', 'D', 'DOV', 'DWDP', 'DPS', 'DTE', 'DUK',
        'DRE', 'DXC', 'ETFC', 'EMN', 'ETN', 'EBAY', 'ECL', 'EIX', 'EW', 'EA', 'EMR', 'ETR',
        'EOG', 'EQT', 'EFX', 'EQIX', 'EQR', 'ESS', 'EL', 'RE', 'ES', 'EXC', 'EXPE', 'EXPD', 
        'ESRX', 'EXR', 'XOM', 'FFIV', 'FB', 'FAST', 'FRT', 'FDX', 'FIS', 'FITB', 'FE', 'FISV',
        'FLIR', 'FLS', 'FLR', 'FMC', 'FL', 'F', 'FTV', 'FBHS', 'BEN', 'FCX', 'GPS', 'GRMN',
        'IT', 'GD', 'GE', 'GGP', 'GIS', 'GM', 'GPC', 'GILD', 'GPN', 'GS', 'GT', 'GWW', 'HAL',
        'HBI', 'HOG', 'HRS', 'HIG', 'HAS', 'HCA', 'HCP', 'HP', 'HSIC', 'HES', 'HPE', 'HLT',
        'HOLX', 'HD', 'HON', 'HRL', 'HST', 'HPQ', 'HUM', 'HBAN', 'HII', 'IDXX', 'INFO', 'ITW',
        'ILMN', 'INCY', 'IR', 'INTC', 'ICE', 'IBM', 'IP', 'IPG', 'IFF', 'INTU', 'ISRG', 'IVZ', 
        'IPGP', 'IQV', 'IRM', 'JBHT', 'JEC', 'SJM', 'JNJ', 'JCI', 'JPM', 'JNPR', 'KSU', 'K', 'KEY',
        'KMB', 'KIM', 'KMI', 'KLAC', 'KSS', 'KHC', 'KR', 'LB', 'LLL', 'LH', 'LRCX', 'LEG', 'LEN',
        'LUK', 'LLY', 'LNC', 'LKQ', 'LMT', 'L', 'LOW', 'LYB', 'MTB', 'MAC', 'M', 'MRO', 'MPC',
        'MAR', 'MMC', 'MLM', 'MAS', 'MA', 'MAT', 'MKC', 'MCD', 'MCK', 'MDT', 'MRK', 'MET', 'MTD',
        'MGM', 'KORS', 'MCHP', 'MU', 'MSFT', 'MAA', 'MHK', 'TAP', 'MDLZ', 'MON', 'MNST', 'MCO',
        'MS', 'MSI', 'MYL', 'NDAQ', 'NOV', 'NAVI', 'NKTR', 'NTAP', 'NFLX', 'NWL', 'NFX', 'NEM',
        'NWSA', 'NWS', 'NEE', 'NLSN', 'NKE', 'NI', 'NBL', 'JWN', 'NSC', 'NTRS', 'NOC', 'NCLH', 
        'NRG', 'NUE', 'NVDA', 'ORLY', 'OXY', 'OMC', 'OKE', 'ORCL', 'PCAR', 'PKG', 'PH', 'PAYX', 
        'PYPL', 'PNR', 'PBCT', 'PEP', 'PKI', 'PRGO', 'PFE', 'PCG', 'PM', 'PSX', 'PNW', 'PXD', 
        'PNC', 'RL', 'PPG', 'PPL', 'PX', 'PFG', 'PG', 'PGR', 'PLD', 'PRU', 'PEG', 'PSA', 'PHM', 
        'PVH', 'QRVO', 'QCOM', 'PWR', 'RRC', 'RJF', 'RTN', 'O', 'RHT', 'REG', 'REGN', 'RF', 'RSG',
        'RMD', 'RHI', 'ROK', 'COL', 'ROP', 'ROST', 'RCL', 'SPGI', 'CRM', 'SBAC', 'SCG', 'SLB', 'STX',
        'SEE', 'SRE', 'SHW', 'SPG', 'SWKS', 'SLG', 'SNA', 'SO', 'LUV', 'SWK', 'SBUX', 'STT', 'SRCL',
        'SYK', 'STI', 'SIVB', 'SYMC', 'SYF', 'SNPS', 'SYY', 'TROW', 'TTWO', 'TPR', 'TGT', 'TEL',
        'FTI', 'TXN', 'TXT', 'BK', 'CLX', 'COO', 'HSY', 'MOS', 'TRV', 'DIS', 'TMO', 'TIF', 'TJX',
        'TMK', 'TSS', 'TSCO', 'TDG', 'TRIP', 'FOXA', 'FOX', 'TSN', 'USB', 'UDR', 'ULTA', 'UAA',
        'UA', 'UNP', 'UAL', 'UNH', 'UPS', 'URI', 'UTX', 'UHS', 'UNM', 'VFC', 'VLO', 'VAR', 
        'VTR', 'VRSN', 'VRSK', 'VZ', 'VRTX', 'VIAB', 'V', 'VNO', 'VMC', 'WMT', 'WBA', 'WM', 
        'WAT', 'WEC', 'WFC', 'WELL', 'WDC', 'WU', 'WRK', 'WY', 'WHR', 'WMB', 'WLTW', 'WYN',
        'WYNN', 'XEL', 'XRX', 'XLNX','XYL', 'YUM', 'ZBH', 'ZION', 'ZTS',]

